In [1]:
import numpy as np

rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

inventory = rng.integers(0, 100, 10)

product_value = price*inventory
product_value

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [5]:
product_value.sort()

product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [6]:
reshaped_product_value = product_value.reshape(2, 5)

reshaped_product_value

array([[ 18.36,  31.15, 141.12, 146.4 , 177.94],
       [212.28, 241.66, 276.  , 285.78, 317.6 ]])

In [7]:
np.median(reshaped_product_value)

np.float64(195.11)

In [9]:
np.percentile(reshaped_product_value, 90)

np.float64(288.962)

In [10]:
np.sqrt(reshaped_product_value)

array([[ 4.28485706,  5.5812185 , 11.87939392, 12.09958677, 13.33941528],
       [14.56983185, 15.54541733, 16.61324773, 16.90502884, 17.82133553]])