In [1]:
import numpy as np

rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

inventory = rng.integers(0, 100, 10)

product_value = price*inventory
product_value

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [ ]:
#out of place sort
np.sort(product_value)

array([ 18.36,  31.15, 141.12, 146.4 , 177.94])

In [5]:
#inplace sort
product_value.sort()
product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [6]:
#reverse array
product_value[::-1]

array([317.6 , 285.78, 276.  , 241.66, 212.28, 177.94, 146.4 , 141.12,
        31.15,  18.36])