In [2]:
import numpy as np

rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [3]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43])

In [5]:
price.mean()

np.float64(5.6)

In [6]:
inventory.mean()

np.float64(35.3)

In [9]:
inventory.min()

np.int64(6)

In [15]:
(price*inventory).argmax()

np.int64(0)

In [17]:
price_2d = price.reshape(5,2)

price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [ ]:
#sum the column
price_2d.sum(axis=0)

array([30.45, 25.55])

In [20]:
#sum the row
price_2d.mean(axis=1)

array([6.315, 3.83 , 3.315, 8.07 , 6.47 ])