In [1]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [2]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [3]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [7]:
price = (rng.random(10) * 10).round(2)
price

array([2.26, 0.17, 8.52, 8.97, 8.06, 9.09, 3.71, 4.11, 3.  , 3.56])

In [10]:
(price * inventory).sum().round(2)

np.float64(3000.87)

In [11]:
inventory_list = list(inventory)
inventory_list

[np.int64(39),
 np.int64(39),
 np.int64(93),
 np.int64(86),
 np.int64(48),
 np.int64(46),
 np.int64(48),
 np.int64(30),
 np.int64(11),
 np.int64(57)]